int lire_long_moy (char *chaine);
int lire_menu_1ou2ou3 (char *chaine);
int lire_menu_1ou2ou3ou4 (char *chaine);
int lire_menu_1ou2ou3ou4ou5 (char *chaine);
int lire_type(char *chaine);
int lire_description(char *chaine);
int lire_nom_ressource(char *chaine);
int lire_1ou2ou3ou4ouq(char *chaine);
int lire_nb_ressource(int *nb_retour);
int lire_menu_1ou2ou3ou4ou5 (char *chaine);
